/**
 * Server-side Pollinations.ai cover generator.
 *
 * Why server-side: the generated bytes are needed both to embed into the MP3
 * ID3 tag and to persist as a /audio/covers/{id}.jpg file referenced by
 * songs.cover_url. Doing it browser-side would require a second round-trip
 * to upload bytes back for ID3 tagging.
 *
 * Endpoint: GET https://gen.pollinations.ai/image/{URL_ENCODED_PROMPT}
 *   query:  model, width, height, seed, nologo, enhance, safe
 *   header: Authorization: Bearer <pk_|sk_...>  (optional)
 *
 * On any failure (timeout / 5xx / network / non-image response) we return
 * undefined and the caller falls back to picsum.photos. The audio gen
 * itself is never blocked by cover-gen failure.
 */

// Use gen.pollinations.ai (current OpenAPI host) — it accepts the full model
// catalogue and Bearer auth lifts to Seed tier. The legacy image.pollinations.ai
// silently routes everything to `sana` regardless of the model param.
const ENDPOINT = 'https://gen.pollinations.ai/image';

export interface PolGenInput {
  prompt: string;
  model: string;
  width: number;
  height: number;
  seed?: number;
  enhance: boolean;
  nologo: boolean;
  safe: boolean;
  apiKey?: string;
  /** Hard timeout in milliseconds. Default 60s — cold-path generation on
   *  the free tier (especially `sana`) can take 60-90s for the first
   *  request to a unique prompt; warm-cache hits return in <1s. 60s is a
   *  realistic budget that keeps audio-gen flow responsive: if Pollinations
   *  is having a slow day, we fall through to picsum for ID3 and leave
   *  cover_url=null (UI shows the seeded gradient). */
  timeoutMs?: number;
}

export interface PolGenResult {
  buffer: Buffer;
  mimeType: 'image/jpeg' | 'image/png';
}

/**
 * Generate a cover image. Returns undefined on any failure — caller is
 * expected to fall back to a default cover provider.
 */
export async function generatePollinationsCover(input: PolGenInput): Promise<PolGenResult | undefined> {
  const timeoutMs = input.timeoutMs ?? 60_000;

  // Pollinations encodes the prompt in the URL path, not as a query param.
  // encodeURIComponent handles spaces, commas, quotes, Cyrillic correctly.
  const path = encodeURIComponent(input.prompt);

  const params = new URLSearchParams();
  if (input.model) params.set('model', input.model);
  if (Number.isFinite(input.width)) params.set('width', String(input.width));
  if (Number.isFinite(input.height)) params.set('height', String(input.height));
  if (Number.isFinite(input.seed)) params.set('seed', String(input.seed));
  // Booleans only sent when true — Pollinations treats absence as default-false.
  if (input.nologo) params.set('nologo', 'true');
  if (input.enhance) params.set('enhance', 'true');
  if (input.safe) params.set('safe', 'true');

  const url = `${ENDPOINT}/${path}?${params.toString()}`;

  const headers: Record<string, string> = {
    'User-Agent': 'ACE-Step-Studio/1.0',
    Accept: 'image/jpeg,image/png,image/*',
  };
  if (input.apiKey) headers.Authorization = `Bearer ${input.apiKey}`;

  const controller = new AbortController();
  const timer = setTimeout(() => controller.abort(), timeoutMs);

  try {
    const res = await fetch(url, { headers, signal: controller.signal, redirect: 'follow' });
    if (!res.ok) {
      // 402 = Pollinations tier-gating. The chosen model (`kontext`,
      // `gptimage*`, `klein`, `wan-image`, `qwen-image`, …) requires
      // Flower/Nectar (paid) tier; the user is on Seed or Anonymous.
      // Auto-pipeline can't recover here — log a clear hint so the user
      // knows to switch the auto-pipeline model in PollinationsPanel to
      // a free-tier one (`flux`, `sana`).
      if (res.status === 402) {
        console.warn(`[pollinations] 402 PAYMENT_REQUIRED for model "${input.model}" — switch to a Seed-tier model (flux, sana) in PollinationsPanel, or upgrade your token at auth.pollinations.ai`);
      } else {
        console.warn(`[pollinations] cover gen failed ${res.status} ${res.statusText}`);
      }
      return undefined;
    }
    const ct = (res.headers.get('content-type') || '').toLowerCase();
    if (!ct.startsWith('image/')) {
      console.warn(`[pollinations] non-image response: ${ct}`);
      return undefined;
    }
    const arrayBuffer = await res.arrayBuffer();
    if (arrayBuffer.byteLength < 256) {
      // Anything <256 bytes is almost certainly an error placeholder.
      console.warn(`[pollinations] suspiciously small response: ${arrayBuffer.byteLength}b`);
      return undefined;
    }
    const mimeType: 'image/jpeg' | 'image/png' = ct.startsWith('image/png') ? 'image/png' : 'image/jpeg';
    return { buffer: Buffer.from(arrayBuffer), mimeType };
  } catch (e: any) {
    if (e?.name === 'AbortError') {
      console.warn(`[pollinations] cover gen timed out after ${timeoutMs}ms`);
    } else {
      console.warn(`[pollinations] cover gen error: ${e?.message || e}`);
    }
    return undefined;
  } finally {
    clearTimeout(timer);
  }
}

/**
 * Derive a stable integer seed from a song UUID for reproducible covers
 * on retake. Hash the first 8 hex chars of the UUID modulo a 31-bit space
 * (Pollinations' seed param accepts up to int32).
 */
export function songIdToSeed(songId: string): number {
  const hex = songId.replace(/-/g, '').slice(0, 8);
  const n = parseInt(hex, 16);
  if (!Number.isFinite(n)) return 0;
  return n & 0x7fffffff;
}
